package com.ssm.domain;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.last_name
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.gender
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.email
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.d_id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.id
     *
     * @return the value of tb_employees.id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.id
     *
     * @param id the value for tb_employees.id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.last_name
     *
     * @return the value of tb_employees.last_name
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.last_name
     *
     * @param lastName the value for tb_employees.last_name
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.gender
     *
     * @return the value of tb_employees.gender
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.gender
     *
     * @param gender the value for tb_employees.gender
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.email
     *
     * @return the value of tb_employees.email
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.email
     *
     * @param email the value for tb_employees.email
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.d_id
     *
     * @return the value of tb_employees.d_id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.d_id
     *
     * @param dId the value for tb_employees.d_id
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

	@Override
	public String toString() {
		return "Employees [id=" + id + ", lastName=" + lastName + ", gender=" + gender + ", email=" + email + ", dId="
				+ dId + "]";
	}
    
    
}