package com.ssm.mapper;

import com.ssm.domain.Dept;
import com.ssm.domain.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    Dept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Mon Jan 18 20:40:17 CST 2021
     */
    int updateByPrimaryKey(Dept record);
}